apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Applications.Cms.Label }}
  namespace: {{ .Values.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 2368
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.Applications.Cms.Label }}